### ISSUE TITLE
Error al correr Pruebas automatizadas GitHub Actions

### ISSUE THREAD

**Issue by OmarVenturaP** [OmarVenturaP/VisualThinkingApp#1]
Al principio al realizar la automatización en el Repositorio de Github, lamentablemente  me generaba problemas, ya que no me corría de manera correcta.

Mi código en test.yml lo tenía de la siguiente forma:
```
name: Run Tests in my project every push on GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
```
Después de investigar un poco y hacer unas preguntas en el apartado de Discussions en la organización de `LaunchX` y obtuve una guía sobre como funcionaria en Windows. El cual queda de la siguiente forma:
```
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run test
      run: yarn test
```

De esta forma y como lo registré en el Commit `8d2e92a311fac585c370bd620e94724409a17936` - "Paso 13)  Modificando archivo GitHub Actions para automatización de pruebas en GitHub" se pudo correr bien el archivo `test.yml` y a partir de ese momento todas las automatizaciones de GitHub Actions corrieron de forma correcta.
